---
# defaults file for roles/role-chrony-controller
ntp_servers:
  - 0.fr.pool.ntp.org
  - 1.fr.pool.ntp.org
  - 2.fr.pool.ntp.org
  - 3.fr.pool.ntp.org

chrony_logdir: /var/log/chrony
chrony_driftfile: /var/lib/chrony/drift
chrony_keyfile: /etc/chrony.keys
chrony_dumpdir: /var/lib/chrony
chrony_hwclockfile: /etc/adjtime