---
# tasks file for roles/role-identity-service

# - include: packages.yml
# - include: configuration.yml
# - include: database.yml
# - include: fernet.yml
# - include: apache.yml
# - include: initialize.yml
# - include: environment.yml

- include: CentOS.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  # ansible_os_family == 'CentOS'
