---
# tasks file for roles/role-chrony-controller

# - name: Include OS-specific variables.
#   include_vars: "{{ ansible_os_family }}.yml"

- include: CentOS.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  # ansible_os_family == 'CentOS'

# - include: Debian.yml
#   when: ansible_os_family == 'Debian'