---

- name: install db client pckges osp-db clients
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb
    - python2-PyMySQL

# - name: start and enable mariadb service
#   service:
#     name: mariadb
#     state: started
#     enabled: yes
