---
# handlers file for roles/role-chrony-nodes
- name: restart chrony
  service:
    name: chrony
    state: restarted
  become: true

- name: restart chronyd
  service:
    name: chronyd
    state: restarted
  become: true